mysql:
  host: 192.168.33.128
  port: 3306
  db: oj_online_server
  user: root
  password: 1225@pdh

redis:
  host: 192.168.33.128
  port: 6379

registry:
  host: localhost
  port: 8500

rabbitmq:
  host: 192.168.33.128
  port: 5672
  user: pengdahong
  password: 1225@pdh
  vhost: '/oj'

jwt:
  key: 'dAjOs8FF6H^df$BXaY@xG!%#AWMgQRbq'

sms:
  accessKeyId: ''
  accessKeySecret: ''
  endpoint: ''
  signName: ''
  templateCode: ''

sandbox:
  - type: c
    host: 192.168.2.129
    port: 5050
  - type: cpp
    host: 192.168.2.129
    port: 5050