version: '3'

networks:
  net:
    name: oj
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1

services:
  consul-dev:
    image: registry.cn-chengdu.aliyuncs.com/aliyun_pdh_space/consul:1.15.4
    container_name: consul-dev
    command: "agent -dev -client=0.0.0.0 -node=dev"
    restart: always
    networks:
      - net
    ports:
      - "8500:8500"

  rabbit-dev:
    image: registry.cn-chengdu.aliyuncs.com/aliyun_pdh_space/rabbitmq:3.13-management
    container_name: rabbit-dev
    restart: always
    volumes:
      - /root/data:/var/lib/rabbitmq
    networks:
      - net
    ports:
      - "5672:5672"
      - "15672:15672"
